services:
  kc-db:
    image: postgres:18.1-alpine3.23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 1s
      retries: 20

  kc:
    image: quay.io/keycloak/keycloak:26.5.0
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    # Both options work
    command: start-dev --db postgres --db-url-host host.docker.internal --db-url-port 5432 --db-username postgres --db-password postgres
    # command: start-dev --db dev-file
    depends_on:
      kc-db:
        condition: service_healthy

  reproduction:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kc
    network_mode: host
